# Generated by Django 2.2.2 on 2019-06-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_bodytext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='bodytext',
            new_name='body_text',
        ),
    ]
