# Generated by Django 2.2.2 on 2019-06-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190621_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body_text',
            field=models.TextField(max_length=1000000),
        ),
    ]
